FROM python:3.12-slim
WORKDIR /app

# dipendenze base
RUN apt-get update && apt-get install -y --no-install-recommends build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
EXPOSE 8000

CMD ["gunicorn", "main:app", "-b", "0.0.0.0:8000", "--workers", "3"]
